apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-agent
  template:
    metadata:
      labels:
        app: k8s-agent
    spec:
      serviceAccountName: k8s-agent-sa
      containers:
      - name: k8s-agent
        image: k8s-agent:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-agent-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-agent-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-agent-role-binding
subjects:
- kind: ServiceAccount
  name: k8s-agent-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-agent-role
  apiGroup: rbac.authorization.k8s.io